### ISSUE TITLE
Mobile Accessability

### ISSUE THREAD

**Issue by PykaRose** [incidentist/the_tuul#23]
Often times, when I try to show people anything to do with making their own videos, one of the first things I'll see is "But I don't have a computer!"

Would it be possible for there to be a button that act as (or with) spacebar for synching the lyrics?
![rufftuulmockup](https://github.com/incidentist/the_tuul/assets/139002823/ad4d0c6a-71cb-47cf-a8a3-2633c56e01ad)

**Comment by incidentist** [comment]
Yuuup this is a great idea. I haven't tried it on my phone at all. Thanks for letting me know that other people are requesting this -- it indicates to me that this is something lots of people will find useful!

**Comment by incidentist** [comment]
@PykaRose A first version of this is live now. You should be able to complete the whole process on mobile, thanks to "Spacebar" and "Enter" buttons. Let me know what you think!
