### ISSUE TITLE
bind to all NICS instead of just loopback and alt port option

### ISSUE THREAD

**Issue by meirlazar** [incidentist/the_tuul#36]
Hey, love this tuul, very cool. I was wondering if there is a way to have the webserver part offer other ports instead of 8000 and more importantly bind to all nics instead of just loopback (localhost/127.0.0.1) so I can make it accessible to the network and with my reverse proxy. You don't have to redevelop the code, if there is a config file somewhere I can modify. Thanks

**Comment by incidentist** [comment]
@meirlazar How do you plan to run The Tuul? There's not a lot of documentation for this yet, but basically there's 2 ways to do it:

## Docker
If you're running it in a Docker container, you can change the port it runs at via docker command line arguments: https://docs.docker.com/network/#published-ports
Something like:
```
npm install
npm run build
docker build .
docker run --rm --network host -p <hostport>:8080 the_tuul
```

Note that Docker exposes the port on all nics by default, so you should be fine there. I think running on the `host` network makes it accessible to other machines on the LAN: https://docs.docker.com/network/network-tutorial-host/

## Django
```
npm install
npm run build
poetry run ./manage.py runserver localhost:<yourport>
```

If these are not what you have in mind, I suggest looking at the Dockerfile and the [Django runserver documentation](https://docs.djangoproject.com/en/5.0/ref/django-admin/#runserver) to see if they can get you where you want to go.

**Comment by meirlazar** [comment]
Excellent. Thanks for the info, I built a docker image from the instructions and it binds to all the NICs, thanks again
